"""
Email Handler
=============
Sends segmentation reports via Gmail SMTP.
Credentials are read from .env  (SENDER_EMAIL, SENDER_PASSWORD).
Supports attaching the generated report file.
"""

import os
import re
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime
from typing import Tuple, Optional

from dotenv import load_dotenv
load_dotenv()

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────

DEFAULT_SUBJECT = "Brain Tumor Segmentation Report – Automated Analysis"

DISCLAIMER = """\
═══════════════════════════════════════════════════════════════
DISCLAIMER
═══════════════════════════════════════════════════════════════
This report was generated by an AI-assisted segmentation system
for research and educational purposes.

It is NOT a substitute for professional medical diagnosis.
All findings MUST be reviewed and validated by a qualified
radiologist or medical specialist before any clinical decision
is made.

Model: 3D U-Net | Framework: PyTorch + MONAI | Dataset: BraTS
═══════════════════════════════════════════════════════════════
"""


# ─────────────────────────────────────────────────────────
# Email body builder
# ─────────────────────────────────────────────────────────

def build_email_body(patient_id: str,
                     institution: str,
                     physician: str,
                     metrics: dict,
                     inference_time: float,
                     dice_score: Optional[float] = None) -> str:
    """
    Build a structured, professional-looking plain-text email body.

    Args:
        patient_id     : patient / case identifier
        institution    : hospital / institution name
        physician      : reporting physician
        metrics        : dict from calculate_all_metrics()
        inference_time : model inference time in seconds
        dice_score     : optional mean Dice (if ground truth available)
    """
    total_vol     = metrics.get("total_tumor_volume_cm3", 0)
    necrotic_vol  = metrics.get("volume_class_1_cm3", 0)
    edema_vol     = metrics.get("volume_class_2_cm3", 0)
    enhancing_vol = metrics.get("volume_class_3_cm3", 0)
    tumor_pct     = metrics.get("tumor_percentage", 0)
    surface_area  = metrics.get("surface_area_mm2", 0)

    tumor_detected = total_vol > 0.0
    detection_str  = "POSITIVE – Tumor regions identified" if tumor_detected \
                     else "NEGATIVE – No significant tumor regions detected"

    dice_line = (f"   Dice Score (vs ground truth) : {dice_score:.4f}\n"
                 if dice_score is not None else "")

    report_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    body = f"""
╔══════════════════════════════════════════════════════════════╗
║        BRAIN TUMOR SEGMENTATION – AUTOMATED REPORT          ║
╚══════════════════════════════════════════════════════════════╝

REPORT DETAILS
──────────────────────────────────────────────────────────────
   Report Date        : {report_date}
   Patient ID         : {patient_id}
   Institution        : {institution}
   Reporting Physician: {physician}
   AI Model           : 3D U-Net (PyTorch + MONAI)

DETECTION RESULT
──────────────────────────────────────────────────────────────
   Status             : {detection_str}

VOLUMETRIC ANALYSIS
──────────────────────────────────────────────────────────────
   Total Tumor Volume    : {total_vol:.2f} cm³
   Necrotic Core (Class 1): {necrotic_vol:.2f} cm³
   Edema         (Class 2): {edema_vol:.2f} cm³
   Enhancing Tumor(Class 3): {enhancing_vol:.2f} cm³
   Tumour Coverage         : {tumor_pct:.2f} % of scanned volume
   Surface Area            : {surface_area:.0f} mm²

MODEL PERFORMANCE
──────────────────────────────────────────────────────────────
   Inference Time    : {inference_time:.2f} s
{dice_line}
CONCLUSION
──────────────────────────────────────────────────────────────
   The AI segmentation pipeline has processed the uploaded MRI
   and classified voxels into background, necrotic core, edema,
   and enhancing tumour regions.  Please find the detailed PDF
   report attached to this email.

{DISCLAIMER}
"""
    return body


# ─────────────────────────────────────────────────────────
# EmailHandler class
# ─────────────────────────────────────────────────────────

class EmailHandler:
    """
    Sends segmentation reports via Gmail SMTP (TLS on port 587).

    Credentials are read from environment variables:
        SENDER_EMAIL    – Gmail address used to send
        SENDER_PASSWORD – Gmail App Password (16-char, NOT your account password)

    To generate a Gmail App Password:
        Google Account → Security → 2-Step Verification → App passwords
    """

    def __init__(self,
                 smtp_server: str = "smtp.gmail.com",
                 smtp_port:   int = 587,
                 sender_email:    Optional[str] = None,
                 sender_password: Optional[str] = None):
        self.smtp_server     = smtp_server
        self.smtp_port       = smtp_port
        self.sender_email    = sender_email    or os.getenv("SENDER_EMAIL", "")
        self.sender_password = sender_password or os.getenv("SENDER_PASSWORD", "")

    # ── Validators ────────────────────────────────────────

    def validate_email(self, email: str) -> Tuple[bool, str]:
        """Basic regex validation of an email address."""
        pattern = r"^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$"
        if re.match(pattern, email.strip()):
            return True, "Valid"
        return False, f"'{email}' does not appear to be a valid email address"

    def _check_config(self) -> Tuple[bool, str]:
        """Verify that sender credentials are set."""
        if not self.sender_email:
            return False, (
                "SENDER_EMAIL is not configured.\n"
                "Add it to your .env file: SENDER_EMAIL=your@gmail.com"
            )
        if not self.sender_password:
            return False, (
                "SENDER_PASSWORD is not configured.\n"
                "Add a Gmail App Password to your .env file: SENDER_PASSWORD=xxxx xxxx xxxx xxxx"
            )
        return True, "OK"

    # ── Core send method ──────────────────────────────────

    def send_report_email(self,
                          recipient_email: str,
                          body_text: str,
                          subject: str = DEFAULT_SUBJECT,
                          attachment_path: Optional[str] = None,
                          patient_id: str = "PATIENT_001") -> Tuple[bool, str]:
        """
        Send a report email, optionally with a file attachment.

        Args:
            recipient_email  : destination address
            body_text        : plain-text email body (use build_email_body())
            subject          : email subject line
            attachment_path  : path to file to attach (PDF, TXT, etc.)
            patient_id       : used only for logging

        Returns:
            (success: bool, message: str)
        """
        # Validate inputs
        ok, err = self._check_config()
        if not ok:
            return False, err

        ok, err = self.validate_email(recipient_email)
        if not ok:
            return False, err

        try:
            msg            = MIMEMultipart()
            msg["From"]    = self.sender_email
            msg["To"]      = recipient_email
            msg["Subject"] = subject

            msg.attach(MIMEText(body_text, "plain", "utf-8"))

            # ── Optional attachment ────────────────────────
            if attachment_path:
                attach_path = Path(attachment_path)
                if attach_path.exists():
                    with open(attach_path, "rb") as fh:
                        part = MIMEBase("application", "octet-stream")
                        part.set_payload(fh.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f'attachment; filename="{attach_path.name}"',
                    )
                    msg.attach(part)
                    logger.info(f"Attached: {attach_path.name}")
                else:
                    logger.warning(f"Attachment not found: {attachment_path}")

            # ── Send ──────────────────────────────────────
            with smtplib.SMTP(self.smtp_server, self.smtp_port,
                              timeout=30) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            logger.info(f"Email sent to {recipient_email} (patient={patient_id})")
            return True, f"Email sent successfully to {recipient_email}"

        except smtplib.SMTPAuthenticationError:
            return False, (
                "SMTP authentication failed.\n"
                "• Make sure you are using a Gmail App Password, not your account password.\n"
                "• Generate one at: Google Account → Security → App passwords"
            )
        except smtplib.SMTPConnectError:
            return False, (
                "Could not connect to Gmail SMTP.\n"
                "Check your internet connection and firewall settings."
            )
        except smtplib.SMTPException as exc:
            return False, f"SMTP error: {exc}"
        except Exception as exc:
            logger.exception("Unexpected error in send_report_email")
            return False, f"Unexpected error: {exc}"

    # ── Batch send ────────────────────────────────────────

    def send_batch_emails(self,
                          recipients: list,
                          body_text: str,
                          subject: str = DEFAULT_SUBJECT,
                          attachment_path: Optional[str] = None,
                          patient_id: str = "PATIENT_001") -> Tuple[int, int, list]:
        """
        Send the same report to multiple recipients.

        Returns:
            (successful_count, failed_count, [(address, error_msg), ...])
        """
        successful, failed = 0, []
        for addr in recipients:
            ok, msg = self.send_report_email(
                addr, body_text, subject, attachment_path, patient_id)
            if ok:
                successful += 1
            else:
                failed.append((addr, msg))
        return successful, len(failed), failed


# ─────────────────────────────────────────────────────────
# Factory
# ─────────────────────────────────────────────────────────

def create_email_handler() -> EmailHandler:
    """Create an EmailHandler from environment variables."""
    return EmailHandler(
        smtp_server=os.getenv("SMTP_SERVER", "smtp.gmail.com"),
        smtp_port=int(os.getenv("SMTP_PORT", 587)),
    )
